apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-wyze-thumbnails
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wyze-shared
  capacity:
    storage: 2Gi
  hostPath:
    path: {{ .Values.volume.wyzeDownloads }}
