apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wyze-integration-secrets
type: Opaque
stringData:
  WYZE_ACCESS_TOKEN: "{{ .Values.wyze.refreshToken }}"
  SLACK_OAUTH_TOKEN: "{{ .Values.slack.token }}"
