apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wyze-integration-secrets
type: Opaque
stringData:
  WYZE_USERNAME: "{{ .Values.wyze.userName }}"
  WYZE_PASSWORD_HASH: "{{ .Values.wyze.passwordHash }}"
  WYZE_KEY_ID: "{{ .Values.wyze.apiKeyId }}"
  WYZE_API_KEY: "{{ .Values.wyze.apiKey }}"
  SLACK_OAUTH_BOT_TOKEN: "{{ .Values.slack.botToken }}"
  SLACK_OAUTH_USER_TOKEN: "{{ .Values.slack.userToken }}"
