FROM golang:1.21.4-alpine3.18 AS build
WORKDIR /build
RUN mkdir /build/bin
COPY . .
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-s" -o /build/bin/wyze-go
FROM scratch AS bin
COPY --from=build /build/bin .
