FROM golang:1.21.4-alpine3.18 AS build
WORKDIR /build
RUN mkdir /build/bin
COPY . .
ARG GOOS=linux
ARG GOARCH=amd64
ENV GOOS=$GOOS
ENV GOARCH=$GOARCH
RUN go build -ldflags "-s" -o /build/bin/wyze-go
FROM scratch AS bin
COPY --from=build /build/bin .
