apiVersion: v1
kind: PersistentVolume
metadata:
  name: wyze-thumbnails
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wyze-shared
  capacity:
    storage: 2Gi
  hostPath:
    path: /home/sjones/wyze-go-download
