apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wyze-thumbnails-mount
spec:
  storageClassName: wyze-shared
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
