# Default values for wyze-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

scheduling:
  cron: "*/5 * * * *"

volume:
  wyzeDownloads: /app/download

wyze:
  camList: ""
  lookbackInSeconds: "300"
  refreshToken: ""

slack:
  token: ""
  channel: ""
